import type { Metadata } from "next"
import { Fraunces, Lato } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"

const mainFont = Fraunces({
	variable: "--font-fraunces",
	subsets: ["latin"],
})

const secondaryFont = Lato({
	variable: "--font-lato",
	weight: ["400","700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${mainFont.variable} ${secondaryFont.variable} bg-background text-foreground font-heading antialiased`}
			>
				<Navbar/>
				{children}
			</body>
		</html>
	)
}
